#!/bin/bash

if [[ "$#" -lt 2 ]]; then
    echo "usage: <freq> <steps per cycle>"
    exit 1
fi

F="$1"
STEPS="$2"

echo "configuration for \"pic18f25k22\" is
end configuration;

// Generated by David with the following settings:
// F = $F
// STEPS = $STEPS

testbench for \"pic18f25k22\" is
begin
    // Pin/Register Actions
    process is
    begin
        wait for 0 ns;
        loop;" 

PI="$(bc -l <<< "scale=12; 4*a(1)")"
W="$(bc -l <<< "scale=12; 2*$PI*$F")"
TSTEP="$(printf "%.0f" $(bc -l <<< "scale=12; 1000000000*1/$F/$STEPS"))"

I=0
T=0
while [[ $I -lt $STEPS ]]; do 
        echo "        //report \"Stimulus actions after $T ns\";
        RA0 <= $(printf "%.0f" $(bc -l <<< "scale=12; 1000000*5*s($W*$T/1000000000)"))uV;
        wait for $TSTEP ns;"
        T=$(bc -l <<< "scale=12; $T + $TSTEP")
        I=$(($I + 1))
done
        
echo "        end loop;
    end process;
end testbench;" 

